In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("olistbr/brazilian-ecommerce")

print("Path to dataset files:", path)

Downloading to C:\Users\dell\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\2.archive...

100%|██████████| 42.6M/42.6M [00:08<00:00, 4.99MB/s]

Extracting files...

Path to dataset files: C:\Users\dell\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2

In [5]:
import kagglehub

path = kagglehub.dataset_download("olistbr/brazilian-ecommerce")

print(path)

C:\Users\dell\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2

In [6]:
import os

print(os.listdir(path))

['olist_customers_dataset.csv', 'olist_geolocation_dataset.csv', 'olist_orders_dataset.csv', 'olist_order_items_dataset.csv', 'olist_order_payments_dataset.csv', 'olist_order_reviews_dataset.csv', 'olist_products_dataset.csv', 'olist_sellers_dataset.csv', 'product_category_name_translation.csv']

In [ ]:
import pandas as pd 
import os

arquivo = os.path.join(path, "olist_orders_dataset.csv")

df = pd.read_csv(arquivo)

df.head() #Verificar arquivo

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [ ]:
print(df.isnull().sum()) # Ver quantidade de itens nulos

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [16]:
print(df['order_status'].value_counts) # Ver os status dos pedidos

<bound method IndexOpsMixin.value_counts of 0        delivered
1        delivered
2        delivered
3        delivered
4        delivered
           ...
99436    delivered
99437    delivered
99438    delivered
99439    delivered
99440    delivered
Name: order_status, Length: 96478, dtype: str>

In [ ]:
df = df[df['order_status'] == 'delivered'] # Filtrar apenas pedidos entregues

print(df.head())

                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00

In [ ]:
colunas_data = [    # Converter datas
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for coluna in colunas_data:
    df[coluna] = pd.to_datetime(df[coluna])

In [ ]:
df['delivery_time'] = (  # Tempo de entrega 
    df['order_delivered_customer_date']
    - df['order_purchase_timestamp']
)

In [20]:
print(df[['delivery_time']].head())

     delivery_time
0  8 days 10:28:40
1 13 days 18:46:08
2  9 days 09:27:40
3 13 days 05:00:36
4  2 days 20:58:23

In [21]:
df['late_delivery'] = ( # Tempo de atraso de entrega
    df['order_delivered_customer_date']
    >
    df['order_estimated_delivery_date']
)

In [ ]:
print(df['late_delivery'].value_counts()) # Contagem de atrasos

late_delivery
False    88652
True      7826
Name: count, dtype: int64

In [26]:
df = df[df['order_status'] == 'delivered'] # Filtrando apenas os entregues
print(df[['order_status']].head())

  order_status
0    delivered
1    delivered
2    delivered
3    delivered
4    delivered

In [ ]:
df['month'] = df['order_purchase_timestamp'].dt.month # Criando coluna de mês

In [ ]:
print(df.groupby('month').size()) #Pedidos por mês

month
1      7819
2      8208
3      9549
4      9101
5     10295
6      9234
7     10031
8     10544
9      4151
10     4743
11     7289
12     5514
dtype: int64

In [ ]:
df.to_csv("orders_cleaned.csv", index=False) # Salvar CSV atualizado

In [32]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:123@localhost:5432/ecommerce_etl" #criando BD
)

In [33]:
df.to_sql(  #subindo dataframe
    'orders',
    engine,
    if_exists='replace',
    index=False
)

C:\Users\dell\AppData\Local\Temp\ipykernel_20104\2490840696.py:1: UserWarning: the 'timedelta' type is not supported, and will be written as integer values (ns frequency) to the database.
  df.to_sql(  #subindo dataframe

478

In [ ]:
arquivo_customers = os.path.join(
    path,
    "olist_customers_dataset.csv"
)

customers_df = pd.read_csv(arquivo_customers)

customers_df.head()   # COLOCANDO A TABELA CUSTOMERS NO pandas

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [ ]:
customers_df.to_sql( # Enviando tabela customers para o BD
    'customers',
    engine,
    if_exists='replace',
    index=False
)

441

In [36]:
df['delivery_days'] = ( #AJUSTANDO NUMERO DE DIAS
    df['order_delivered_customer_date']
    - df['order_purchase_timestamp']
).dt.days

In [37]:
df.drop(columns=['delivery_time'], inplace=True) #REMOVENDO COLUNA COM ERRO NO BI

In [ ]:
df.to_sql( #subindo coluna novamente 
    'orders',
    engine,
    if_exists='replace',
    index=False
)

478